const { BgColors, BrightColors, Logger, TextColors, TextStyles } = require("../dist"); // require('term-logger');

console.log("---------------------- LOGGER ----------------------");
Logger.cluster("CLUSTER event test");
Logger.command("COMMAND event test");
Logger.complete("COMPLETE event test");
Logger.critical("CRITICAL event test");
Logger.database("DATABASE event test");
Logger.debug("DEBUG event test");
Logger.error("ERROR event test");
Logger.event("EVENT event test");
Logger.fatal("FATAL event test");
Logger.info("INFO event test");
Logger.note("NOTE event test");
Logger.pending("PENDING event test");
Logger.ready("READY event test");
Logger.shard("SHARD event test");
Logger.start("START event test");
Logger.success("SUCCESS event test");
Logger.waiting("WAITING event test");
Logger.warn("WARN event test");
Logger.watch("WATCH event test");

console.log("---------------------- TEXT STYLES ----------------------");
TextStyles.bold("BOLD");
TextStyles.dim("DIM");
TextStyles.hidden("HIDDEN");
TextStyles.inverse("INVERSE");
TextStyles.italic("ITALIC");
TextStyles.strikethrough("STRIKETHROUGH");
TextStyles.underline("UNDERLINE");
TextStyles.visible("VISIBLE");

console.log("---------------------- TEXT COLORS ----------------------");
TextColors.blue("BLUE");
TextColors.cyan("CYAN");
TextColors.gray("GRAY");
TextColors.green("GREEN");
TextColors.purple("PURPLE");
TextColors.red("RED");
TextColors.white("WHITE");
TextColors.yellow("YELLOW");

console.log("---------------------- BRIGHT COLORS ----------------------");
BrightColors.blue("BLUE");
BrightColors.cyan("CYAN");
BrightColors.green("GREEN");
BrightColors.purple("PURPLE");
BrightColors.red("RED");
BrightColors.white("WHITE");
BrightColors.yellow("YELLOW");

console.log("---------------------- BACKGROUND COLORS ----------------------");
BgColors.blue("BLUE");
BgColors.cyan("CYAN");
BgColors.gray("GRAY");
BgColors.green("GREEN");
BgColors.purple("PURPLE");
BgColors.red("RED");
BgColors.white("WHITE");
BgColors.yellow("YELLOW");
